[build]
  command = "corepack enable && corepack prepare pnpm@8.15.4 --activate && pnpm install && pnpm exec next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" # evita que Netlify intente usar npm por defecto
  NEXT_PRIVATE_TARGET = "server" # asegura compatibilidad con funciones lambda

[[plugins]]
  package = "@netlify/next"
