[build]
  command = "npm install -- && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  GIT_SSH_COMMAND = "ssh -o StrictHostKeyChecking=no"

[[plugins]]
  package = "@netlify/next"
